# brew install pdftk-java

all: pdf

pdf:
	pdftk A=python.pdf cat A1-3 output cover.pdf
	pdftk A=python.pdf cat A4-5 output 01.pdf
	pdftk A=python.pdf cat A6-9 output 02.pdf
	pdftk A=python.pdf cat A10-15 output 03.pdf
	pdftk A=python.pdf cat A16-18 output 04.pdf
	pdftk A=python.pdf cat A19-22 output 05.pdf
	pdftk A=python.pdf cat A23-26 output 06.pdf
	pdftk A=python.pdf cat A27-30 output 07.pdf
	pdftk A=python.pdf cat A31-34 output 08.pdf
	pdftk A=python.pdf cat A35-38 output 09.pdf
	pdftk A=python.pdf cat A39-42 output 10.pdf
	pdftk A=python.pdf cat A43-46 output 11.pdf
	pdftk A=python.pdf cat A47-50 output 12.pdf
	pdftk A=python.pdf cat A51-54 output 13.pdf
	pdftk A=python.pdf cat A55-56 output 14.pdf
	pdftk A=python.pdf cat A57-58 output 15.pdf

