# brew install pdftk-java

all: pdf

pdf:
	pdftk A=python.pdf cat A1-3 output cover.pdf
	pdftk A=python.pdf cat A4-6 output 01.pdf
	pdftk A=python.pdf cat A7-10 output 02.pdf
	pdftk A=python.pdf cat A11-16 output 03.pdf
	pdftk A=python.pdf cat A17-19 output 04.pdf
	pdftk A=python.pdf cat A20-23 output 05.pdf
	pdftk A=python.pdf cat A24-27 output 06.pdf
	pdftk A=python.pdf cat A28-31 output 07.pdf
	pdftk A=python.pdf cat A32-35 output 08.pdf
	pdftk A=python.pdf cat A36-39 output 09.pdf
	pdftk A=python.pdf cat A40-43 output 10.pdf
	pdftk A=python.pdf cat A44-47 output 11.pdf
	pdftk A=python.pdf cat A48-51 output 12.pdf
	pdftk A=python.pdf cat A52-55 output 13.pdf
	pdftk A=python.pdf cat A56-57 output 14.pdf
	pdftk A=python.pdf cat A58-59 output 15.pdf

